server:
  port: 8050

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false

spring:
  data:
    mongodb:
      uri: mongodb+srv://awsguru202:awsguru202@cluster0-dvas1.mongodb.net/test?w=majority
      database: automotive
