version: '3.4'
services:
  config-service:
    build: ./automotive-config
    image: mmsalem/automotive-config
    ports:
      - '8888:8888'
    networks:
      - fms_app_net
      
  registry-service:
    build: ./automotive-registery
    image: mmsalem/automotive-registery
    ports:
      - '8761:8761'
    depends_on:
      - config-service
    networks:
      - fms_app_net

  gateway-service:
    build: ./automotive-gateway
    image: mmsalem/automotive-gateway
    ports:
      - '8080:8080'
    depends_on:
      - config-service
      - registry-service
      - vehicle-service
      - customer-service
      - status-service
    networks:
      - fms_app_net

  vehicle-service:
    build: ./automotive-vehicles
    image: mmsalem/automotive-vehicles
    ports:
      - '8050:8050'
    depends_on:
      - config-service
      - registry-service
    networks:
      - fms_app_net
      
  customer-service:
    build: ./automotive-customer
    image: mmsalem/automotive-customer
    ports:
      - '8051:8051'
    depends_on:
      - config-service
      - registry-service
    networks:
      - fms_app_net
      
  status-service:
    build: ./automotive-vehicles-status
    image: mmsalem/automotive-vehicles-status
    ports:
      - '8052:8052'
    depends_on:
      - config-service
      - registry-service
      - vehicle-service
      - customer-service
    networks:
      - fms_app_net

  simulator-service:
    build: ./automotive-simulator
    image: mmsalem/automotive-simulator
    ports:
      - '8053:8053'
    depends_on:
      - config-service
      - registry-service
      - vehicle-service
      - customer-service
    networks:
      - fms_app_net

networks:
  fms_app_net:
    driver: bridge