server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  profiles:
    active:
    - native
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"